### ISSUE TITLE
在阿里云函数计算上没法成功运行

### ISSUE THREAD

**Issue by zhanpeng1996** [YanWenKun/ComfyUI-Docker#11]
![WX20231018-164139](https://github.com/YanWenKun/ComfyUI-Docker/assets/38784558/4237d922-243c-4a76-8d42-e63b37525725)
已经看到一些正在下载的日志，但是没法访问。

**Comment by YanWenKun** [comment]
这段输出是正在下载模型文件（使用 aria2），下方的报错是健康检查端口 8188（ComfyUI 的访问界面）没有响应。因为还在下载模型文件，ComfyUI 还没启动，所以 8188 端口肯定是没有响应。
我建议你找找健康检查相关的设置，把超时时间延长。

另外一种思路则和本镜像区别比较大：使用“All-in-one”的镜像，把用到的模型都塞里面。
可以参考：
https://github.com/chadly/comfy_ui

**Comment by zhanpeng1996** [comment]
感谢
