### ISSUE TITLE
docker build 构建失败

### ISSUE THREAD

**Issue by huangyichun** [YanWenKun/ComfyUI-Docker#12]
=> ERROR [stage-0 3/8] RUN --mount=type=cache,target=/root/.cache/pip     pip install --brea  5.1s
------                                                                                              
 > [stage-0 3/8] RUN --mount=type=cache,target=/root/.cache/pip     pip install --break-system-packages         --pre -U xformers         --index-url https://download.pytorch.org/whl/cu121         --extra-index-url https://pypi.org/simple:                                                             
0.269 Looking in indexes: https://download.pytorch.org/whl/cu121, https://pypi.org/simple           
4.554 Collecting xformers                                                                           
4.566   Using cached xformers-0.0.23.dev685.tar.gz (3.8 MB)
4.909   Preparing metadata (setup.py): started
4.972   Preparing metadata (setup.py): finished with status 'error'
4.974   error: subprocess-exited-with-error
4.974   
4.974   × python setup.py egg_info did not run successfully.
4.974   │ exit code: 1
4.974   ╰─> [6 lines of output]
4.974       Traceback (most recent call last):
4.974         File "<string>", line 2, in <module>
4.974         File "<pip-setuptools-caller>", line 34, in <module>
4.974         File "/tmp/pip-install-i23mgr98/xformers_9108ab734a45421f94f5381a3e74f6d4/setup.py", line 23, in <module>
4.974           import torch
4.974       ModuleNotFoundError: No module named 'torch'
4.974       [end of output]
4.974   
4.974   note: This error originates from a subprocess, and is likely not a problem with pip.
4.975 error: metadata-generation-failed
4.975 
4.975 × Encountered error while generating package metadata.
4.975 ╰─> See above for output.
4.975 
4.975 note: This is an issue with the package mentioned above, not pip.
4.975 hint: See above for details.
------
Dockerfile:20
--------------------
  19 |     # Install xFormers (dev version, will install PyTorch as well)
  20 | >>> RUN --mount=type=cache,target=/root/.cache/pip \
  21 | >>>     pip install --break-system-packages \
  22 | >>>         --pre -U xformers \
  23 | >>>         --index-url https://download.pytorch.org/whl/cu121 \
  24 | >>>         --extra-index-url https://pypi.org/simple
  25 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --break-system-packages         --pre -U xformers         --index-url https://download.pytorch.org/whl/cu121         --extra-index-url https://pypi.org/simple" did not complete successfully: exit code: 1

**Comment by YanWenKun** [comment]
这报错是“找不到 torch”，我猜很有可能是网络问题，挂上代理试试吧
