### ISSUE TITLE
Could not select driver

### ISSUE THREAD

**Issue by moritz-t-w** [YanWenKun/ComfyUI-Docker#13]
`Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]`
I have an nvidia gpu. Idk what info I should provide, just tell me and I'll follow up.

**Comment by moritz-t-w** [comment]
Using docker run:
```
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container:
```

**Comment by moritz-t-w** [comment]
I have the proprietary `nvidia` driver package installed

**Comment by shaiksuhel1999** [comment]
Hi,
In my case also getting the same error when I'm trying to run the docker container using the below command
 
 docker run --gpus all image-id
 
 **docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].**
 
 
Basically I have Created VM using the default Amzon AMI which is verified by Amazon
 
 These are AMI details
 
 GPU (Kernel 4.14)
 AMI name: amzn2-ami-ecs-gpu-hvm-2.0.20231103-x86_64-ebs
 ECS Agent version: 1.79.0
 Docker version: 20.10.25
 Containerd version: 1.6.19
 NVIDIA driver version: 535.54.03
 CUDA version: 12.2.0
 Source AMI name: amzn2-ami-minimal-hvm-2.0.20230926.0-x86_64-ebs
 
 
 I'm using the below commands to erase the old nvidia-driver (535.54.03)and trying to install new nvidia-driver(535.129.03) version  with below commands which are given in aws documentation
 
sudo yum remove nvidia*
sudo yum remove cuda*
sudo yum erase nvidia cuda
sudo yum update -y
sudo amazon-linux-extras install kernel-5.15
sudo yum install gcc make && sudo yum update -y
sudo reboot
sudo yum install -y gcc kernel-devel-$(uname -r)
chmod +x NVIDIA-Linux-x86_64*.run
sudo CC=/usr/bin/gcc10-cc ./NVIDIA-Linux-x86_64*.run
sudo touch /etc/modprobe.d/nvidia.conf
echo "options nvidia NVreg_EnableGpuFirmware=0" | sudo tee --append /etc/modprobe.d/nvidia.conf
sudo reboot
 
After following the Above commands I'm able to upgrade nvidia-driver version to 535.129.03 And kernel also I'm able to upgrade to 5.15,
But when I'm Running docker container facing the above mentioned issue.
 
 Any Suggestions?

**Comment by YanWenKun** [comment]
Hi @moritz-t-w @shaiksuhel1999 , could you provide me some information by running `nvidia-smi` ?

Since "could not select device driver" error occurs from vastly different reasons, we need to narrow down the scope first.
From my experience, old version drivers & kernels should be fine, as long as it's working.
You can run one of those NVIDIA's docker image and run `nvidia-smi` to make sure docker works fine with GPU driver:

`docker run -it --rm --gpus all nvidia/cuda:12.1.1-base-ubi9 nvidia-smi`
or
`docker run -it --rm --gpus all nvidia/cuda:12.1.1-base-ubuntu22.04 nvidia-smi`

**Comment by shaiksuhel1999** [comment]
Thanks @YanWenKun for response and find below details

This is the result of **nvidi-smi** command


[root~]# nvidia-smi

+---------------------------------------------------------------------------------------+

| NVIDIA-SMI 535.129.03              Driver Version: 535.129.03    CUDA Version: 12.2     |

|-----------------------------------------+----------------------+----------------------+

| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |

| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |

|                                         |                      |               MIG M. |

|=========================================+======================+======================|

|   0  Tesla T4                       On  | 00000000:00:1E.0 Off |                    0 |

| N/A   19C    P8               9W /  70W |      2MiB / 15360MiB |      0%      Default |

|                                         |                      |                  N/A |

+-----------------------------------------+----------------------+----------------------+
 
+---------------------------------------------------------------------------------------+

| Processes:                                                                            |

|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |

|        ID   ID                                                             Usage      |

|=======================================================================================|

|  No running processes found                                                           |

+---------------------------------------------------------------------------------------+



**One Information:**

OS in host machine - Amazon Linux 2

**Comment by YanWenKun** [comment]
@shaiksuhel1999  I don't have an ECS GPU instance at hand, but based on your info I would check NVIDIA Container Toolkit, try run:
`sudo nvidia-ctk runtime configure --runtime=docker && sudo systemctl restart docker`

If `nvidia-ctk` doesn't exist, follow these steps to install it:

```bash
# Import NVIDIA's repository
curl -s -L https://nvidia.github.io/libnvidia-container/stable/amzn2/nvidia-container-toolkit.repo | \
  sudo tee /etc/yum.repos.d/nvidia-container-toolkit.repo

# Note: use the general RPM repo if not using Amazon Linux 2. 
#curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
#  sudo tee /etc/yum.repos.d/nvidia-container-toolkit.repo

# Disable incompatible dependency
sudo yum-config-manager --disable amzn2-graphics

# Install the toolkit
sudo yum clean expire-cache && sudo yum install nvidia-container-toolkit

# Re-enable dependency
sudo yum-config-manager --enable amzn2-graphics

# Configure Docker to recognize NVIDIA Container Runtime
sudo nvidia-ctk runtime configure --runtime=docker && sudo systemctl restart docker
```

(Docs:
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
https://medium.com/avs-it/run-cog-containers-on-aws-with-nvidia-t4-tensor-core-gpus-cb0e0e20abd0 )

@moritz-t-w Hope this will help you too.

**Comment by moritz-t-w** [comment]
Ok thank you very mich! I'll try this and get back to ya

**Comment by moritz-t-w** [comment]
@YanWenKun ...can I just install this?
```
aur/nvidia-container-toolkit 1.13.5-1 (+40 4.44) (Out-of-date: 2023-09-07) 
```

**Comment by moritz-t-w** [comment]
Nope I cannot. I will try to do this some other time and leave the issue open for now. Don't have time to install yum cause there's some missing deps and there's gonna be conflicts between package managers I think.
Trying either of the docker commands you sent:
```
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```
nvidia-smi:
```
Sun Dec  3 16:50:57 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4070 Ti     Off | 00000000:01:00.0  On |                  N/A |
|  0%   31C    P5              19W / 285W |    696MiB / 12282MiB |     28%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1661      G   /usr/lib/Xorg                               280MiB |
|    0   N/A  N/A      1825      G   /usr/bin/gnome-shell                        144MiB |
|    0   N/A  N/A      2088      G   livewallpaper                                17MiB |
|    0   N/A  N/A      2499      G   ...sion,SpareRendererForSitePerProcess       22MiB |
|    0   N/A  N/A      4308      G   ...rdCache,DocumentPictureInPictureAPI       61MiB |
|    0   N/A  N/A      4682      G   /usr/lib/firefox/firefox                    149MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by shaiksuhel1999** [comment]
Thanks @YanWenKun , I sorted out the issue.. when we are using the nvidia/cuda base docker image no need of installing the drivers inside the container.. base image will refer from host machine.
removed the driver installation from my docker file.
