### ISSUE TITLE
docker如何设置其他model位置

### ISSUE THREAD

**Issue by dhlsam** [YanWenKun/ComfyUI-Docker#14]
docker如何设置其他model位置
ComfyUI-Docker安装成功，但是nas里安装了其他画图docker，如何在docker里软连接其他程序的model文件夹位置

**Comment by YanWenKun** [comment]
软链接用 `ln -s` 命令，具体你搜一下指南

目录对应关系： 

| ComfyUI 目录 | stable-diffusion-webui 目录 |
| ------------- | ------------- |
| models/checkpoints  | models/Stable-diffusion  |
| models/controlnet  | models/ControlNet  |
| models/embeddings | embeddings |
| models/loras | models/Lora |
| models/vae | models/VAE |
