### ISSUE TITLE
Please add package that can install insightface

### ISSUE THREAD

**Issue by NicoNicoNico123** [YanWenKun/ComfyUI-Docker#16]
As I have issue to install this package : https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID with original dockerfile
I have manually adjust of add package of python311-devel in dockerfile

**Comment by YanWenKun** [comment]
Thanks, you nailed it. Installing `insightface` does require `python311-devel` package as well as `Cython` and `cmake`.
