### ISSUE TITLE
issues when runing AMD ROCm 6.0.2 RX7800XT

### ISSUE THREAD

**Issue by hqnicolas** [YanWenKun/ComfyUI-Docker#18]
########################################
Starting ComfyUI...
########################################
** ComfyUI startup time: 2024-02-15 21:29:54.642845
** Platform: Linux
** Python version: 3.11.7 (main, Dec 15 2023, 10:49:17) [GCC]
** Python executable: /usr/bin/python3
** Log path: /home/runner/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Manager

Traceback (most recent call last):
  File "/home/runner/ComfyUI/main.py", line 76, in <module>
    import execution
  File "/home/runner/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/home/runner/ComfyUI/nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "/home/runner/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/home/runner/ComfyUI/comfy/sd.py", line 3, in <module>
    from comfy import model_management
  File "/home/runner/ComfyUI/comfy/model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/runner/ComfyUI/comfy/model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/torch/cuda/__init__.py", line 803, in current_device
    _lazy_init()
  File "/usr/lib64/python3.11/site-packages/torch/cuda/__init__.py", line 318, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No HIP GPUs are available

#################################################################################
Command to reproduce:
#################################################################################
docker run -it \
  --name comfyui \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/home/runner \
  --env CLI_ARGS="--use-pytorch-cross-attention" \
  --device=/dev/kfd --device=/dev/dri/card0 --device=/dev/dri \
  --group-add=root --ipc=host --cap-add=SYS_PTRACE \
  --security-opt seccomp=unconfined \
  yanwk/comfyui-boot:rocm
  #################################################################################
  
  Basesystem instalation:
  
  intel 12700h + 7800xt
  ROCm 6.0.2
  
  https://gist.github.com/hqnicolas/6d9bfa997667626742c0918b95e67171
  
    #################################################################################
    
   I have Stable Diffusion runing. but this ComfyUI is hard!

**Comment by YanWenKun** [comment]
I just upgraded ROCm version of PyTorch to 6.0 in Dockerfile. Hope it would solve the problem!

**Comment by hqnicolas** [comment]
Thank you! 
Testing now!

**Comment by hqnicolas** [comment]
This is the HIP Manual:  https://rocm.docs.amd.com/projects/HIP/en/latest/how_to_guides/install.html
#############################
This is the command to verify HIP GPU installation:
/opt/rocm/bin/hipconfig --full
#############################
This is my sistem return:

opt/rocm$ /opt/rocm/bin/hipconfig --full
HIP version  : 6.0.32831-204d35d16

== hipconfig
HIP_PATH     : /opt/rocm-6.0.2
ROCM_PATH    : /opt/rocm-6.0.2
HIP_COMPILER : clang
HIP_PLATFORM : amd
HIP_RUNTIME  : rocclr
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__= -D__HIP_PLATFORM_AMD__= -I/opt/rocm-6.0.2/include -I/opt/rocm-6.0.2/lib/llvm/lib/clang/17.0.0
 

== hip-clang
HIP_CLANG_PATH   : /opt/rocm-6.0.2/llvm/bin
AMD clang version 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-6.0.2 24012 af27734ed982b52a9f1be0f035ac91726fc697e4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-6.0.2/llvm/bin
Configuration file: /opt/rocm-6.0.2/lib/llvm/bin/clang++.cfg
AMD LLVM version 17.0.0git
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: alderlake

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
hip-clang-cxxflags :  -isystem "/opt/rocm-6.0.2/include" -O3
hip-clang-ldflags  : --driver-mode=g++ -O3 --hip-link --rtlib=compiler-rt -unwindlib=libgcc

=== Environment Variables
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin

== Linux Kernel
Hostname     : nicolas-cpu
Linux nicolas-cpu 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

**Comment by hqnicolas** [comment]
I think this is a case to Hipify
https://github.com/ROCm/HIPIFY/blob/amd-staging/README.md

**Comment by YanWenKun** [comment]
@hqnicolas Wait, before selling your AMD card, take a look at DirectML!

Currently I don't have an AMD GPU at hand, but weeks ago I managed to run ComfyUI on Windows 11 with WSL2 with AMD 4800H APU. WSL is not as neat as Docker, but reinstalling WSL distros was easy. DirectML is slower than ROCm but still significant faster than CPU. Here is my note:

https://github.com/YanWenKun/ComfyUI-Docker/blob/main/docs/wsl-directml.adoc

Hope it helps!

**Comment by hqnicolas** [comment]
Updating the way I run ROCm aplication.
https://gist.github.com/hqnicolas/d9d939934a441ab8e1dcb23ebbcd5709
next week I will test it with [ComfyUI-Docker](https://github.com/YanWenKun/ComfyUI-Docker)

**Comment by YanWenKun** [comment]
@hqnicolas I have rebuilt `rocm` Docker image, although I guess ZLUDA is more practical (I tested it on Win11 with RX6800, works on most basic workflows eg. txt2img, img2img)

**Comment by hqnicolas** [comment]
it was working here with ZLUDA

**Comment by Enissay** [comment]
I ran into the same issue. Not clear what worked here since links are dead. 
Please update @hqnicolas

**Comment by hqnicolas** [comment]
> I ran into the same issue. Not clear what worked here since links are dead. 
> Please update @hqnicolas 

It's just the AMD ROCm running stable diffusion 
https://github.com/hqnicolas/StableDiffusionROCm

I change the gist to an repo
