### ISSUE TITLE
Support for Google Coral TPU

### ISSUE THREAD

**Issue by ra4el** [YanWenKun/ComfyUI-Docker#19]
Is it possible to add support for the Google Coral TPU?

**Comment by YanWenKun** [comment]
I don't have one so just guess:

1. Pull an image that can run PyTorch on TPU https://github.com/pytorch/xla#docker 
2. Run a container and:

```sh
git clone https://github.com/comfyanonymous/ComfyUI.git
cd ComfyUI
conda install --yes --file requirements.txt
python main.py --listen --port 8188
```
