### ISSUE TITLE
需要python311-dbm来运行ComfyUI Workspace Manager

### ISSUE THREAD

**Issue by dmahacker** [YanWenKun/ComfyUI-Docker#26]
这个node：https://github.com/11cafe/comfyui-workspace-manager
需要安装python311-dbm，希望可以在镜像里带上这个

**Comment by YanWenKun** [comment]
感谢提醒，也让我发现了一个好用的工具 :)

**Comment by Weixuanf** [comment]
我才发现我们的插件需要dbm。。。应该是因为model manager里用shelve做cache。估计之后会migrate到sqlite，就不需要额外的dependency了

**Comment by YanWenKun** [comment]
@Weixuanf 感谢作者大大！插件真的很实用 🥳

**Comment by Weixuanf** [comment]
感谢作者的支持！我最近也在用docker deploy comfyui，所以发现了这个repo，很好的参考～谢谢！
