### ISSUE TITLE
Pre-installing default custom nodes

### ISSUE THREAD

**Issue by liusida** [YanWenKun/ComfyUI-Docker#28]
I am setting up several ComfyUI containers and would love to automate the installation of popular custom nodes for each container.

Is there a good way to configure the container to pre-install certain custom nodes for me?

For example, I think it'll be great to have a file that contains all the URLs for the custom nodes, and they can be installed automatically.

Thanks.

**Comment by YanWenKun** [comment]
I have a big all-in-one image [`megapak`](https://github.com/YanWenKun/ComfyUI-Docker/tree/main/megapak) , which handles many denpendencies ComfyUI custom nodes would need, and a long `download.sh` which will download 30+ popular custom nodes.

For now I recommend modifying `megapak` for custom deployment.

And yeah, a user script for custom nodes make sense. But custom nodes need Python dependencies. Currently for users, click-install in ComfyUI-Manager would handle that. I need to figure out how that could be done for a user-defined list.
(Or maybe requesting a batch-install feature for ComfyUI-Manager?)

**Comment by liusida** [comment]
Thanks, I'll take a look at megapak.
