### ISSUE TITLE
SD 模型集成

### ISSUE THREAD

**Issue by yumc2573** [YanWenKun/ComfyUI-Docker#29]
镜像中有计划集成SD模型吗？

**Comment by YanWenKun** [comment]
`latest` 镜像是不会了，留空交给用户决定吧~
[`megapak`](https://github.com/YanWenKun/ComfyUI-Docker/tree/main/megapak) 镜像可能会加少量，比如现在下载列表里就有 [Playground 2.5](https://huggingface.co/playgroundai/playground-v2.5-1024px-aesthetic)，以后SD3出了也会加。
直接集成到镜像里应该是不会了，那样镜像就太大了
