### ISSUE TITLE
opensuse/tumbleweed python3.10

### ISSUE THREAD

**Issue by VisualFox** [YanWenKun/ComfyUI-Docker#3]
Hi YanWenKun,

Thank you for your work! :)

I am not too familiar with openSUSE but it seems that the binary for python3.10 is not installed as python3 but python3.10. 

When I try to start the container I am getting this error: 
`home/scripts/entrypoint.sh: line 25: python3: command not found`

Changing python3 to python3.10 in entrypoint.sh  solved my issue

**Comment by chadly** [comment]
thanks! this fixed it for me as well

**Comment by YanWenKun** [comment]
Thanks for your work!
And sorry for being late. It's been a long summer...😖 I'm going to update this repo thoroughly.
