### ISSUE TITLE
启动Docker提示fatal: could not create work tree dir 'ComfyUI': Permission denied

### ISSUE THREAD

**Issue by totothink** [YanWenKun/ComfyUI-Docker#31]
`mkdir -p storage

docker run -it \
  --name comfyui \
  --gpus all \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/home/runner \
  -e CLI_ARGS="" \
  yanwk/comfyui-boot:latest`

在终端执行上面的命令后，提示以下错误：

`########################################
[INFO] Downloading ComfyUI & Manager...
########################################
+ cd /home/runner
+ git clone --depth=1 --no-tags --recurse-submodules --shallow-submodules https://github.com/comfyanonymous/ComfyUI.git
fatal: could not create work tree dir 'ComfyUI': Permission denied
+ cd /home/runner/ComfyUI
/home/scripts/download.sh: line 13: cd: /home/runner/ComfyUI: No such file or directory`

**Comment by YanWenKun** [comment]
这是对存储目录没有写权限，能问下你用的是什么环境吗？是WSL2还是Linux？


------------------ 原始邮件 ------------------
发件人: aaron ***@***.***&gt;
发送时间: 2024年4月25日 10:46
收件人: YanWenKun/ComfyUI-Docker ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [YanWenKun/ComfyUI-Docker] 启动Docker提示fatal: could not create work tree dir 'ComfyUI': Permission denied (Issue #31)





 
`mkdir -p storage
 
docker run -it 
 --name comfyui 
 --gpus all 
 -p 8188:8188 
 -v "$(pwd)"/storage:/home/runner 
 -e CLI_ARGS="" 
 yanwk/comfyui-boot:latest`
 
在终端执行上面的命令后，提示以下错误：
 
`########################################
 [INFO] Downloading ComfyUI &amp; Manager...
 ########################################
  
cd /home/runner 

git clone --depth=1 --no-tags --recurse-submodules --shallow-submodules https://github.com/comfyanonymous/ComfyUI.git
 fatal: could not create work tree dir 'ComfyUI': Permission denied 

cd /home/runner/ComfyUI
 /home/scripts/download.sh: line 13: cd: /home/runner/ComfyUI: No such file or directory`

**Comment by YanWenKun** [comment]
试试这个吧：

```sh
docker rm comfyui

mkdir -p storage

# 强制文件权限
sudo chown -R 1000:1000 storage

# root权限运行
docker run -it \
  --name comfyui \
  --gpus all \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/home/runner \
  -e CLI_ARGS="" \
  yanwk/comfyui-boot:latest
```

如果还不行，改成 root 权限运行：

```sh
sudo docker run -it \
  --name comfyui \
  --gpus all \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/home/runner \
  -e CLI_ARGS="" \
  yanwk/comfyui-boot:latest
```

如果依然不行，改用内外 root：

```sh
sudo docker run -it \
  --name comfyui \
  --gpus all \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/home/runner \
  -e CLI_ARGS="" \
  --user root \
  --workdir /root \
  yanwk/comfyui-boot:latest \
  /bin/bash /home/scripts/root-wrapper.sh
```

**Comment by YanWenKun** [comment]
@openkava CoreOS 下可以试试这个版本： [`megapak`](https://github.com/YanWenKun/ComfyUI-Docker/blob/main/megapak/README.zh.adoc)
更适合 rootless 部署。
（但是这个镜像在 Windows + WSL2 下会有另外的目录权限问题，所以我在 `latest` 镜像里还是用了传统的配置方式）

**Comment by wirytiox** [comment]
sorry for reopening this. i just want to leave a comment in a english version;
the fix is running the docker container as root:
```
docker run -it \
  --name comfyui \    # the name of the container.
  --gpus all \
  --user root \            # THE CHANGE THAT MAKES IT WORK
  -p 8188:8188 \
  -v "$(pwd)"/home/USERNAME/sukaaa:/home/runner \    #remember to change username
  -e CLI_ARGS="" \
  yanwk/comfyui-boot:latest
```
That should do the trick. IF YOU ARE ON WSL2 run this inside the ubuntu machine. this is stored in ubuntu and not in docker-desktop. i still have no clue where the docker volumes are saved. the path reported by the `docker inspect` doesn't even exist.
