### ISSUE TITLE
有办法绕开拉取吗？一直卡着了。。。。

### ISSUE THREAD

**Issue by abmmmm** [YanWenKun/ComfyUI-Docker#32]
要哭死了，一直卡这里
########################################
[INFO] Downloading ComfyUI & Manager...
########################################
+ cd /home/runner
+ git clone --depth=1 --no-tags --recurse-submodules --shallow-submodules https://github.com/comfyanonymous/ComfyUI.git
fatal: destination path 'ComfyUI' already exists and is not an empty directory.
+ cd /home/runner/ComfyUI
+ git pull
Updating 1c4af59..0bdc2b1
error: Your local changes to the following files would be overwritten by merge:
	comfy/ldm/modules/attention.py
	comfy/ldm/modules/diffusionmodules/model.py
	comfy/ldm/modules/diffusionmodules/openaimodel.py
Please commit your changes or stash them before you merge.
Aborting
########################################
[INFO] Downloading ComfyUI & Manager...
########################################
+ cd /home/runner
+ git clone --depth=1 --no-tags --recurse-submodules --shallow-submodules https://github.com/comfyanonymous/ComfyUI.git
fatal: destination path 'ComfyUI' already exists and is not an empty directory.
+ cd /home/runner/ComfyUI
+ git pull
fatal: unable to access 'https://github.com/comfyanonymous/ComfyUI.git/': Recv failure: Connection timed out
我下载个塞进去了都，但是容器日志还是报错，说啥没拉取，现在是半夜十一点五十，从六点下班开始弄的，很想哭。。。。

**Comment by YanWenKun** [comment]
嗨呀，文档第一节有写呀，建立一个空白文件 `./storage/.download-complete` 就可以了

```
touch ./storage/.download-complete
```

---

除了这个方法，你还可以更彻底地解决问题：加个配置代理的脚本。毕竟后续各种自定义节点免不了科学上网。

建立文件 `./storage/scripts/set-proxy.sh` 并编辑：

```bash
#!/bin/bash
set -eu

export HTTP_PROXY=http://host.docker.internal:1081
export HTTPS_PROXY=$HTTP_PROXY
export http_proxy=$HTTP_PROXY
export https_proxy=$HTTP_PROXY
export NO_PROXY="localhost,*.local,*.internal,[::1],fd00::/7,
10.0.0.0/8,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.168.0.0/16,
10.*,127.*,169.254.*,172.16.*,172.17.*,172.18.*,172.19.*,172.20.*,
172.21.*,172.22.*,172.23.*,172.24.*,172.25.*,172.26.*,172.27.*,
172.28.*,172.29.*,172.30.*,172.31.*,172.32.*,192.168.*,
*.cn,ghproxy.com,*.ghproxy.com,ghproxy.org,*.ghproxy.org,
gh-proxy.com,*.gh-proxy.com,ghproxy.net,*.ghproxy.net"
export no_proxy=$NO_PROXY
echo "[INFO] 代理设置为 $HTTP_PROXY"
```

**Comment by abmmmm** [comment]
> 嗨呀，文档第一节有写呀，建立一个空白文件 就可以了`./storage/.download-complete`
> 
> ```
> touch ./storage/.download-complete
> ```
> 
> 除了这个方法，你还可以更彻底地解决问题：加个配置代理的脚本。毕竟后续各种自定义节点免不了科学上网。
> 
> 建立文件 并编辑：`./storage/scripts/set-proxy.sh`
> 
> ```shell
> #!/bin/bash
> set -eu
> 
> export HTTP_PROXY=http://host.docker.internal:1081
> export HTTPS_PROXY=$HTTP_PROXY
> export http_proxy=$HTTP_PROXY
> export https_proxy=$HTTP_PROXY
> export NO_PROXY="localhost,*.local,*.internal,[::1],fd00::/7,
> 10.0.0.0/8,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.168.0.0/16,
> 10.*,127.*,169.254.*,172.16.*,172.17.*,172.18.*,172.19.*,172.20.*,
> 172.21.*,172.22.*,172.23.*,172.24.*,172.25.*,172.26.*,172.27.*,
> 172.28.*,172.29.*,172.30.*,172.31.*,172.32.*,192.168.*,
> *.cn,ghproxy.com,*.ghproxy.com,ghproxy.org,*.ghproxy.org,
> gh-proxy.com,*.gh-proxy.com,ghproxy.net,*.ghproxy.net"
> export no_proxy=$NO_PROXY
> echo "[INFO] 代理设置为 $HTTP_PROXY"
> ```

我人傻了，这一步我做了，但是是建立的文件夹，感谢回复！我这就去试试！
