### ISSUE TITLE
安装ComfyUI_Custom_Nodes_AlekPet报错，尝试手动安装缺失module直接无法启动

### ISSUE THREAD

**Issue by valleyss** [YanWenKun/ComfyUI-Docker#33]
### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
Node -> DeepTranslatorNode [Loading]
Node -> ExtrasNode [Loading]
Node -> GoogleTranslateNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet/__init__.py", line 164, in <module>
    from .DeepTranslatorNode.deep_translator_node import DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet/DeepTranslatorNode/deep_translator_node.py", line 7, in <module>
    import deep_translator
ModuleNotFoundError: No module named 'deep_translator'

Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet module for custom nodes: No module named 'deep_translator'

Import times for custom nodes:
   0.0 seconds: /home/runner/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/runner/ComfyUI/custom_nodes/AIGODLIKE-ComfyUI-Translation
   0.0 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.2 seconds: /home/runner/ComfyUI/custom_nodes/OneButtonPrompt
   0.2 seconds: /home/runner/ComfyUI/custom_nodes/images-grid-comfy-plugin
   0.3 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Manager
   0.3 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.4 seconds: /home/runner/ComfyUI/custom_nodes/comfyui-workspace-manager
   0.5 seconds: /home/runner/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.6 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-NegiTools
   1.0 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   1.1 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_kkTranslator_nodes
   4.1 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Crystools
   7.8 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
  10.1 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_InstantID
  33.7 seconds (IMPORT FAILED): /home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet

Starting server

To see the GUI go to: http://0.0.0.0:8188
FETCH DATA from: /home/runner/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1514988643_custom-node-list.json [DONE]
FETCH DATA from: /home/runner/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/746607195_github-stats.json [DONE]
FETCH DATA from: /home/runner/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json [DONE]
FETCH DATA from: /home/runner/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]

**Comment by valleyss** [comment]
我把缺失模块补全后似乎httpcore缺少SyncHTTPTransport
### [END] ComfyUI AlekPet Nodes ###
Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet/__init__.py", line 166, in <module>
    from .GoogleTranslateNode.google_translate_node import GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet/GoogleTranslateNode/google_translate_node.py", line 6, in <module>
    from googletrans import Translator, LANGUAGES
  File "/home/runner/.local/lib/python3.11/site-packages/googletrans/__init__.py", line 6, in <module>
    from googletrans.client import Translator
  File "/home/runner/.local/lib/python3.11/site-packages/googletrans/client.py", line 25, in <module>
    class Translator:
  File "/home/runner/.local/lib/python3.11/site-packages/googletrans/client.py", line 55, in Translator
    proxies: typing.Dict[str, httpcore.SyncHTTPTransport] = None, timeout: Timeout = None):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'httpcore' has no attribute 'SyncHTTPTransport'

Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet module for custom nodes: module 'httpcore' has no attribute 'SyncHTTPTransport'

Import times for custom nodes:
   0.0 seconds: /home/runner/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/runner/ComfyUI/custom_nodes/AIGODLIKE-ComfyUI-Translation
   0.0 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.1 seconds: /home/runner/ComfyUI/custom_nodes/images-grid-comfy-plugin
   0.1 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.1 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /home/runner/ComfyUI/custom_nodes/OneButtonPrompt
   0.2 seconds: /home/runner/ComfyUI/custom_nodes/comfyui-workspace-manager
   0.2 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-NegiTools
   0.2 seconds: /home/runner/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.3 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.4 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_kkTranslator_nodes
   2.7 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   3.3 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Crystools
   3.6 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_InstantID
  33.8 seconds (IMPORT FAILED): /home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet

Starting server

To see the GUI go to: http://0.0.0.0:8188

**Comment by valleyss** [comment]
解决了。谢谢httpcore.AsyncHTTPProxy

**Comment by YanWenKun** [comment]
看起来是科学上网问题，我给更新一下文档，突出一些
