### ISSUE TITLE
root用户运行docker脚本，报错 Permission denied: '/home/runner/ComfyUI/user'

### ISSUE THREAD

**Issue by fanqinghui** [YanWenKun/ComfyUI-Docker#34]
docker run -it \
>   --name comfyui \
>   --gpus all \
>   -p 8188:8188 \
>   -v "$(pwd)"/storage:/home/runner \
>   -e CLI_ARGS="" \
>   yanwk/comfyui-boot:latest
[INFO] No pre-start script found. Skipping.
########################################
[INFO] Starting ComfyUI...
########################################
Total VRAM 32501 MB, total RAM 79928 MB
pytorch version: 2.3.0+cu121
There was a problem when trying to write in your cache folder (/home/runner/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla V100-SXM2-32GB : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
Traceback (most recent call last):
  File "/home/runner/./ComfyUI/main.py", line 206, in <module>
    server = server.PromptServer(loop)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/ComfyUI/server.py", line 71, in __init__
    self.user_manager = UserManager()
                        ^^^^^^^^^^^^^
  File "/home/runner/ComfyUI/app/user_manager.py", line 20, in __init__
    os.mkdir(user_directory)
PermissionError: [Errno 13] Permission denied: '/home/runner/ComfyUI/user'

**Comment by YanWenKun** [comment]
啥环境，WSL2 or Linux?
