### ISSUE TITLE
启动后 AttributeError: _ARRAY_API not found

### ISSUE THREAD

**Issue by flycocke** [YanWenKun/ComfyUI-Docker#37]
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

**Comment by lfnt3** [comment]
I have the same issue.

comfyui     | Traceback (most recent call last):  File "/home/runner/./ComfyUI/main.py", line 217, in <module>
comfyui     |     init_custom_nodes()
comfyui     |   File "/home/runner/ComfyUI/nodes.py", line 1999, in init_custom_nodes
comfyui     |     if not load_custom_node(os.path.join(extras_dir, node_file)):
comfyui     |   File "/home/runner/ComfyUI/nodes.py", line 1906, in load_custom_node
comfyui     |     module_spec.loader.exec_module(module)
comfyui     |   File "/home/runner/ComfyUI/comfy_extras/nodes_canny.py", line 1, in <module>
comfyui     |     from kornia.filters import canny
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/__init__.py", line 8, in <module>
comfyui     |     from . import augmentation, color, contrib, core, enhance, feature, io, losses, metrics, morphology, tracking, utils, x
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/__init__.py", line 2, in <module>
comfyui     |     from kornia.augmentation import auto, container
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/auto/__init__.py", line 1, in <module>
comfyui     |     from .autoaugment import AutoAugment
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/auto/autoaugment/__init__.py", line 1, in <module>
comfyui     |     from .autoaugment import AutoAugment
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/auto/autoaugment/autoaugment.py", line 5, in <module>
comfyui     |     from kornia.augmentation.auto.base import SUBPOLICY_CONFIG, PolicyAugmentBase
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/auto/base.py", line 5, in <module>
comfyui     |     from kornia.augmentation.auto.operations.base import OperationBase
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/auto/operations/__init__.py", line 3, in <module>
comfyui     |     from .policy import PolicySequential
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/auto/operations/policy.py", line 7, in <module>
comfyui     |     from kornia.augmentation.container.base import ImageSequentialBase, TransformMatrixMinIn
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/container/__init__.py", line 1, in <module>
comfyui     |     from kornia.augmentation.container.augment import AugmentationSequential
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/container/augment.py", line 4, in <module>
comfyui     |     from kornia.augmentation._2d.base import RigidAffineAugmentationBase2D
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/_2d/__init__.py", line 2, in <module>
comfyui     |     from kornia.augmentation._2d.intensity import *
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/_2d/intensity/__init__.py", line 28, in <module>
comfyui     |     from kornia.augmentation._2d.intensity.plasma import RandomPlasmaBrightness, RandomPlasmaContrast, RandomPlasmaShadow
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/augmentation/_2d/intensity/plasma.py", line 5, in <module>
comfyui     |     from kornia.contrib import diamond_square
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/contrib/__init__.py", line 15, in <module>
comfyui     |     from .image_stitching import ImageStitcher
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/contrib/image_stitching.py", line 7, in <module>
comfyui     |     from kornia.feature import LocalFeatureMatcher, LoFTR
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/feature/__init__.py", line 43, in <module>
comfyui     |     from .lightglue_onnx import OnnxLightGlue
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/feature/lightglue_onnx/__init__.py", line 1, in <module>
comfyui     |     from .lightglue import OnnxLightGlue
comfyui     |   File "/usr/lib/python3.11/site-packages/kornia/feature/lightglue_onnx/lightglue.py", line 14, in <module>
comfyui     |     import onnxruntime as ort
comfyui     |   File "/usr/lib64/python3.11/site-packages/onnxruntime/__init__.py", line 23, in <module>
comfyui     |     from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
comfyui     |   File "/usr/lib64/python3.11/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
comfyui     |     from .onnxruntime_pybind11_state import *  # noqa
comfyui     | AttributeError: _ARRAY_API not found

**Comment by YanWenKun** [comment]
Fixed in bcbb027cf6a5ac9fd4cbf18995ba846b04747d98 :-)
