### ISSUE TITLE
Initial download of Models with aria2c  does not respect proxy environment variables

### ISSUE THREAD

**Issue by lasdem** [YanWenKun/ComfyUI-Docker#39]
In download.sh the following line fails to download models because my environment is behind a mandatory proxy server that I have specified with HTTP_PROXY and HTTPS_PROXY environment variables. 

This line causes the issue: 
```
aria2c --input-file=/home/scripts/download.txt \
    --allow-overwrite=false --auto-file-renaming=false --continue=true \
    --max-connection-per-server=5
```
I had to connect into the container and change the file to the following to get it to work.
```
aria2c --input-file=/home/scripts/download.txt \
    --allow-overwrite=false --auto-file-renaming=false --continue=true \
    --max-connection-per-server=5 --all-proxy=http://myproxy:3128
```

Now that I write this, I realize I could probably have used `--all-proxy=$HTTP_PROXY` or something like that to make it work generically.

**Comment by YanWenKun** [comment]
I have reproduced your issue. 

Aria2 did respect env vars, but only [lower-case](https://aria2.github.io/manual/en/html/aria2c.html#environment).

So you probably need ([example file](https://github.com/YanWenKun/ComfyUI-Docker/blob/main/megapak/runner-scripts/set-proxy.sh.example)):

```
HTTP_PROXY=
HTTPS_PROXY=
http_proxy=
https_proxy=
NO_PROXY=
no_proxy=
```

I tested and it works.

...And I have to say, case-sensitive env-vars are confusing 🤯 ...

**Comment by lasdem** [comment]
thanks!
