### ISSUE TITLE
新版又一个问题来了，旧版没问题，怪哉

### ISSUE THREAD

**Issue by flycocke** [YanWenKun/ComfyUI-Docker#41]
Traceback (most recent call last):
  File "/root/./ComfyUI/main.py", line 78, in <module>
    import comfy.utils
  File "/root/ComfyUI/comfy/utils.py", line 1, in <module>
    import torch
  File "/usr/local/lib64/python3.11/site-packages/torch/__init__.py", line 239, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

**Comment by YanWenKun** [comment]
我也遇到了，正在排查，奇了怪了，文件明明在老地方呆着，环境变量也好好的

**Comment by matiasba** [comment]
@YanWenKun Could it be posible to start tagging each build with a date or a version? It would make possible to go back to a working version when something like this happens

**Comment by YanWenKun** [comment]
结果是灯下黑，从：
`/usr/lib/python3.11/site-packages`
变成：
`/usr/local/lib/python3.11/site-packages`

现在Python库有至少四个常见窝点了😂
```
/usr/local/lib64/python3.11/site-packages/
/usr/local/lib/python3.11/site-packages/
/usr/lib/python3.11/site-packages/
/usr/lib64/python3.11/site-packages/
```

**Comment by YanWenKun** [comment]
> @YanWenKun Could it be posible to start tagging each build with a date or a version? It would make possible to go back to a working version when something like this happens

Done!

**Comment by flycocke** [comment]
@YanWenKun 为了3dPACK升级了版本，但其实3dPACK是无法正常加载的。
/root/.local/lib/python3.11/site-packages/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
