### ISSUE TITLE
ComfyUI-3D-Pack  EGL/egl.h: No such file or directory

### ISSUE THREAD

**Issue by flycocke** [YanWenKun/ComfyUI-Docker#42]
/usr/local/lib/python3.11/site-packages/nvdiffrast/torch/../common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by jaunkst** [comment]
same, are we missing libEGL ?

**Comment by flycocke** [comment]
I tried installing libgl, but it still went wrong

**Comment by YanWenKun** [comment]
fixed in 9345e44c7e5f1b531f5a3360505477df3facd56d
