### ISSUE TITLE
crash after using the container for a while

### ISSUE THREAD

**Issue by wirytiox** [YanWenKun/ComfyUI-Docker#44]
after running pony models, trt convertion or anything somewhat intensive it just crashes saying there was a error in line 42 of entrypoint.sh.
[comfyui_8188.prev2.log](https://github.com/user-attachments/files/16262630/comfyui_8188.prev2.log)
The odd things is that i don't see any python error. it just crashes. i'll try a few more times

**Comment by wirytiox** [comment]
it seems that having a node that fails to load causes instability? it doesn't seem to happen anymore

**Comment by YanWenKun** [comment]
Not sure, but OOM could cause crash, I/O stuck could freeze app. I would recommend disabling unnecessary custom nodes.
