### ISSUE TITLE
大佬有没测试过最新megapak版本？从获取镜像到下载完执行后就是显示[F glutil.cpp:338] eglInitialize() failed

### ISSUE THREAD

**Issue by flycocke** [YanWenKun/ComfyUI-Docker#45]
[F glutil.cpp:338] eglInitialize() failed
/runner-scripts/entrypoint.sh: line 52:  1705 Aborted                 (core dumped) python3 ./ComfyUI/main.py --listen --port 8188 ${CLI_ARGS}

**Comment by flycocke** [comment]
另外建议给所有插件git下载时打上hash版本，不然任何插件更新都会影响整体的运行

**Comment by YanWenKun** [comment]
刚生成了个新镜像，试了下，正常启动，能跑 TripoSR 工作流

nvdiffrast/glutil 的问题应该是之前 #42 的问题，加了 libEGL-devel 修复了，还出问题得看详细日志了

排查 pak7 出的问题，可能是 LinuxWheels 编译时 CUDA 版本没覆盖到（但之前调整过，再出问题的概率不大），
后续考虑换 Comfy3D 作者那版轮子：
https://github.com/MrForExample/Comfy3D_Pre_Builds/tree/main/_Build_Wheels/_Wheels_linux_py311_cu121

打版本就搞复杂了，ComfyUI 这种狂飙猛进式的生态，搞版本管理真不如多做快照了
如果担心插件更新出岔子，可以先看看 [nodecafe](https://www.nodecafe.co/nodes) 的安装情况

**Comment by YanWenKun** [comment]
刚更新了镜像，换成了 MrForExample/Comfy3D_Pre_Builds 的编译版本
