### ISSUE TITLE
megapak [F glutil.cpp:338] eglInitialize() failed

### ISSUE THREAD

**Issue by Shougakusei** [YanWenKun/ComfyUI-Docker#46]
Hello!

I tried to run megapak, and experienced such problem

```
[comfy_mtb] | INFO -> loaded 78 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://None:8188/mtb if you want more information.
Warn!: xFormers is available (Attention)
[F glutil.cpp:338] eglInitialize() failed
Aborted (core dumped)
```

Do you have any idea how to fix it?

my CUDA version is 12.5 if it matters. Running container on linux via docker

![image](https://github.com/user-attachments/assets/c4636e63-e3cd-4007-a418-8405ad911fab)

**Comment by YanWenKun** [comment]
Same as #45 

I just did a full test again, and I can't reproduce this issue.

I'll try to replace some wheels, maybe it can solve the problem.

PS. CUDA 12.5 is totally fine, my setup on Fedora 40:

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.58.02              Driver Version: 555.58.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA TITAN Xp                Off |   00000000:09:00.0  On |                  N/A |
| 27%   43C    P8             16W /  250W |    1358MiB /  12288MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
```

**Comment by flycocke** [comment]
我尝试了几日，如果用torch=2.30，会要求 numpy>=2.0, 但 onnxruntime-gpu 当前1.18.1 版本 只能支持 numpy<2 ，所以我尝试了退回torch=2.2.2 ，即刻没问题了，但问题来了，3dpack的whl是默认要求torch=2.30，所以whl 有没支持 torch2.2.2以下版本的很重要。

**Comment by flycocke** [comment]
@YanWenKun 能否编译一个torch=2.2.2的

**Comment by YanWenKun** [comment]
> 我尝试了几日，如果用torch=2.30，会要求 numpy>=2.0, 但 onnxruntime-gpu 当前1.18.1 版本 只能支持 numpy<2 ，所以我尝试了退回torch=2.2.2 ，即刻没问题了，但问题来了，3dpack的whl是默认要求torch=2.30，所以whl 有没支持 torch2.2.2以下版本的很重要。

Torch 默认用 numpy 2.0.1 ，但你改用 1.26.4 是兼容的， [镜像里目前的版本](https://github.com/YanWenKun/ComfyUI-Docker/actions/runs/10091924549/job/27904487336#step:8:3227) 即是，兼容正常。

额外提一句，如果用 ComfyUI-Manager 安装插件，会有一个 pip 安装过程，有些插件可能破坏原有的依赖关系，而 Manager 并不是很智能，只关心最新安装的插件。好在 megapak 默认设了`PIP_USER=true` ，运行时安装的 Python 包都在 /root/.local 下，清理即可恢复。

> 能否编译一个torch=2.2.2的

这恐怕不光是一个 PT222 的事。我也有打算将 Comfy3D 完全剥离出来，作单独的镜像，但那需要时间。

着急用的话，这里有两个 PT2.2.2 的 Windows 整合包，有个 [高手](https://github.com/YanWenKun/ComfyUI-Windows-Portable/issues/7#issuecomment-2241790191) 玩得挺溜的
https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.9
https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.10

**Comment by YanWenKun** [comment]
@Shougakusei I have updated the packages used by Comfy3D, which caused this error. Give it a try (use the new image) and see if `eglInitialize() failed` happens again.
(In that case, I will remove packages for Comfy3D in `megapak`, and have a new image dedicated for Comfy3D.)

**Comment by Shougakusei** [comment]
@YanWenKun I pulled new docker image, problem remains. Didn't remove old ComfyUI files from storage. Do I need to, or script updated packages automatically?

**Comment by Shougakusei** [comment]
I don't need Comfy3D so far, so if you will make separate image for 3D it will solve my problem

**Comment by Shougakusei** [comment]
@YanWenKun
I've tested cu124-megapak and it worked! ヽ(・∀・)ﾉ
Thank you for help!
