### ISSUE TITLE
about root permission

### ISSUE THREAD

**Issue by 0913ktg** [YanWenKun/ComfyUI-Docker#47]
Hello, thank you for your contribution.

I am currently using the yanwk/comfyui-boot:cu121 image to create and use a container.
I am using the runner user, but I need root user privileges, so I am inquiring about this.

How can I use root privileges?
Can you provide the password?

Thank you.

**Comment by ycrao** [comment]
@0913ktg 

```bash
docker exec -it --user root {your_comfyui-boot_container_id} /bin/bash 
```

**Comment by YanWenKun** [comment]
@ycrao Thanks for help!

@0913ktg Another solution is using [cu121-megapak](https://github.com/YanWenKun/ComfyUI-Docker/blob/main/cu121-megapak/README.adoc) or [cu124-megapak](https://github.com/YanWenKun/ComfyUI-Docker/blob/main/cu124-megapak/README.adoc). They are using root by design.
