### ISSUE TITLE
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by MrUSBEN** [YanWenKun/ComfyUI-Docker#5]
OS: Ubuntu 22
Driver: Nvidia driver 535
Device id 0 when checked in nvidia-smi. 
But i still get this error , how to fix?

**Comment by ricardoccpaiva** [comment]
@MrUSBEN https://github.com/NVIDIA/nvidia-docker/issues/1034
