### ISSUE TITLE
该镜像跑在k8s里面报错

### ISSUE THREAD

**Issue by sufeng** [YanWenKun/ComfyUI-Docker#51]
![WX20240806-171634](https://github.com/user-attachments/assets/d974fc45-a604-436e-8197-0a5722f77551)

为什么还需要安装GPU驱动？

**Comment by YanWenKun** [comment]
不是装驱动，而是为容器启用 GPU 支持，让容器内能访问 GPU

[NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)

https://github.com/NVIDIA/k8s-device-plugin

https://www.jimangel.io/posts/nvidia-rtx-gpu-kubernetes-setup/

**Comment by sufeng** [comment]
ok 万分感谢 我再试试 有k8s环境成果再分享出来

**Comment by sufeng** [comment]
![WX20240807-172112-comfyui](https://github.com/user-attachments/assets/f9339dcd-f1f0-4d01-a155-2e328f6dda0c)

在k8s + containerd 环境已跑通 tag cu121，针对国内环境修改了一下模型下载地址
