### ISSUE TITLE
Unable to run the FP8 Checkpoint version

### ISSUE THREAD

**Issue by BaptisteTrocquet** [YanWenKun/ComfyUI-Docker#52]
I've just run the container and it works great with my previous workflow made with SDXL 1.5. However, I've tried to run the following workflow using FLUX fp8-checkpoint-version : 

https://comfyanonymous.github.io/ComfyUI_examples/flux/flux_dev_checkpoint_example.png

Unfortunately, it doesn't work. I've got the following message :

model weight dtype torch.float8_e4m3fn, manual cast: torch.float32
model_type FLUX
Using xformers attention in VAE
Using xformers attention in VAE
Model doesn't have a device attribute.
Model doesn't have a device attribute.
Requested to load FluxClipModel_
Loading 1 new model
Requested to load Flux
Loading 1 new model
/runner-scripts/entrypoint.sh: line 52:     9 Killed                  python3 ./ComfyUI/main.py --listen --port 8188 ${CLI_ARGS}

**Comment by YanWenKun** [comment]
Sorry for being late!

I would recommend using `cu124-megapak` image, and run the Schnell edition of Flux:

https://comfyanonymous.github.io/ComfyUI_examples/flux/flux_schnell_checkpoint_example.png

If that's still not working, try this edited workflow of flux_schnell_example.png :

[flux_schnell_fp8.json](https://github.com/user-attachments/files/16728158/flux_schnell_fp8.json)

(It's using more fp8)
