### ISSUE TITLE
能针对国内的环境搞一个嘛，模型文件下载不下来

### ISSUE THREAD

**Issue by Harry-675** [YanWenKun/ComfyUI-Docker#53]

**Comment by YanWenKun** [comment]
要得呀，我找时间整一个用 https://hf-mirror.com 的版本吧，或者做成参数形式

顺便也加速一下用 huggingface_cli 下模型的那些自定义节点

**Comment by YanWenKun** [comment]
吼吼，整了个全新的，试试看吧！
https://github.com/YanWenKun/ComfyUI-Docker/tree/main/cu124-cn

**Comment by tianyu150** [comment]
这个版本没有了码？

**Comment by YanWenKun** [comment]
确实有再出个新的CN镜像的打算，在考虑用cu130还是cu132
