### ISSUE TITLE
The ` /home/runner` directory inside the contianer seems to be owned by root, causing Permission denied error

### ISSUE THREAD

**Issue by vivagonna** [YanWenKun/ComfyUI-Docker#6]
```
+ cd /home/runner
+ git clone --depth=1 --no-tags --recurse-submodules --shallow-submodules https://github.com/comfyanonymous/ComfyUI.git
fatal: could not create work tree dir 'ComfyUI': Permission denied
+ cd /home/runner/ComfyUI
/home/scripts/download.sh: line 12: cd: /home/runner/ComfyUI: No such file or directory
```
The mapped host directory has full permissions, the container failed to start due to Permission denied error. Anyway to fix this without having the container running as root user?

**Comment by vivagonna** [comment]
after added --user 99:100, the permission denied error was worked around, however ran into another permissions issue:
`chmod: changing permissions of '/home/scripts/download.sh': Operation not permitted`

**Comment by YanWenKun** [comment]
Sorry for being late!
That's an old issue... And I have a workaround in `docker-compose.yml`, which chown before running comfyui.
Maybe this can help you: https://github.com/docker/compose/issues/3270
Using `docker run -v ...` should be fine.
