### ISSUE TITLE
请教一下，该镜像是否支持k8s containerd rootless部署运行？有人部署跑过rootless吗 podman也行 不知道怎么部署

### ISSUE THREAD

**Issue by sufeng** [YanWenKun/ComfyUI-Docker#61]

**Comment by YanWenKun** [comment]
cu124-cn 就是 rootless-ready 啊，文档里也有 podman 运行方法。除了cu121，其他几个也是 rootless-ready，我就是在 Fedora 下用 rootless podman 开发的。你先试试本地 podman 跑起来吧，记得先安装配置NV显卡容器工具



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sufeng ***@***.***&gt;
发送时间: 2024年10月12日 11:09
收件人: YanWenKun/ComfyUI-Docker ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [YanWenKun/ComfyUI-Docker] 请教一下，该镜像是否支持k8s containerd rootless部署运行？有人部署跑过rootless吗 podman也行 不知道怎么部署 (Issue #61)

**Comment by YanWenKun** [comment]
呃，阿里云镜像已经有几个月没更新了，而且也没有cu124目录，不知道你咋配上的？
