### ISSUE TITLE
permission denied for git clone

### ISSUE THREAD

**Issue by lijiang-long** [YanWenKun/ComfyUI-Docker#63]
Thanks for putting this together. I have an issue using this docker image. When I do the docker run, it gives an error message saying that git clone comfyUI failed. If I move git clone from download.sh to the Dockerfile, it works. Any suggestions?

**Comment by YanWenKun** [comment]
It could be 'permission denied' for `storage` folder. This happens on Docker Desktop on WSL2 (you mount the volume as a low-privillege user, but inside container runs a root user). See: https://github.com/YanWenKun/ComfyUI-Docker/blob/main/cu121-megapak/README.adoc#note---for-wsl2-users

**Comment by lijiang-long** [comment]
Thanks for the quick response! I end up using the megapak and it works using the default settings. the cu121 itself doesn't work.
