### ISSUE TITLE
comfy3d-pt25 docker跑了报错 请教一下

### ISSUE THREAD

**Issue by sufeng** [YanWenKun/ComfyUI-Docker#66]
ubuntu 22.04 
docker 23
镜像：yanwk/comfyui-boot:comfy3d-pt25
运行命令：
docker run -it --rm \
  --name comfy3d-pt25 \
  --gpus 1 \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/root \
  -e PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple" \
  -e HF_ENDPOINT="https://hf-mirror.com" \
  -e CLI_ARGS="" \
  docker.rainbond.cc/yanwk/comfyui-boot:comfy3d-pt25

报错信息：
![image](https://github.com/user-attachments/assets/57dc623e-18d4-4e5a-a22b-94120c76c6f8)

**Comment by YanWenKun** [comment]
可能需要更新，我得晚点处理。另外用不着最新版的话，pt23一样的

**Comment by YanWenKun** [comment]
更新完简单测试了一下，最新的 Hunyuan3D 可以跑，次新一点的 SF3D 报错，TripoSR 毫无悬念能跑，其他的没什么意思就没测了。
3D 系列的兼容性问题会继续存在，毕竟 PyTorch3D 这套体系并不是为了工业应用而生的。Torch C++ 扩展需要像着色器一样现编译，虽然方便科研人员快速发布代码验证概念、展示成果，但在部署运维侧就是灾难了。
