### ISSUE TITLE
Comfy3D pt25 not starting eglInitialize() failed

### ISSUE THREAD

**Issue by jurassicjordan** [YanWenKun/ComfyUI-Docker#69]
```docker run -it --rm   --name comfy3d-pt25   --gpus all   -p 8188:8188   -v "$(pwd)"/DockerCont:/root   -e CLI_ARGS=""   yanwk/comfyui-boot:comfy3d-pt25
[INFO] Running set-proxy script...
[INFO] Continue without proxy.
[INFO] Running pre-start script...
[INFO] Continue without pre-start script.
########################################
[INFO] Starting ComfyUI...
########################################
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-22 21:44:18.971984
** Platform: Linux
** Python version: 3.12.7 (main, Oct 01 2024, 15:35:42) [GCC]
** Python executable: /usr/bin/python3
** ComfyUI Path: /root/ComfyUI
** Log path: /root/comfyui.log

Prestartup times for custom nodes:
   0.5 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 11931 MB, total RAM 31960 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: /root/ComfyUI/web
/usr/local/lib/python3.12/site-packages/kiui/nn/__init__.py:31: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

/usr/local/lib/python3.12/site-packages/kiui/nn/__init__.py:37: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_bwd

/root/ComfyUI/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/TriplaneGaussian/utils/ops.py:38: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float32)

/root/ComfyUI/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/TriplaneGaussian/utils/ops.py:44: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd

Warn!: xFormers is available (Attention)
Warn!: /usr/local/lib64/python3.12/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(

[F1122 21:44:42.427187812 glutil.cpp:338] eglInitialize() failed
/runner-scripts/entrypoint.sh: line 52:     9 Aborted                 (core dumped) python3 ./ComfyUI/main.py --listen --port 8188 ${CLI_ARGS}
```

**Comment by YanWenKun** [comment]
I have reproduced this issue on WSL2 Docker, but on native Linux (in my case, Fedora 41 with latest akmod NVIDIA driver) this isn't happening.

I guess this could be a driver issue. I'm trying to find out the cause.

But before that, try [pt23](https://github.com/YanWenKun/ComfyUI-Docker/tree/main/comfy3d-pt23) or [StableFast3D-WinPortable](https://github.com/YanWenKun/StableFast3D-WinPortable) or [ComfyUI-Windows-Portable](https://github.com/YanWenKun/ComfyUI-Windows-Portable) instead.

**Comment by jurassicjordan** [comment]
Pt23 seems to be working fine-ish? It was working until at random it decided to reinstall all of comfy3D's dependancies again and now it's stuck. Btw I am running the dockers on Linux EndeavourOS

**Comment by jurassicjordan** [comment]
> Pt23 seems to be working fine-ish? It was working until at random it decided to reinstall all of comfy3D's dependancies again and now it's stuck. Btw I am running the dockers on Linux EndeavourOS

this is a separate issue for Pt23, I'm going to make a new issue on it

**Comment by YanWenKun** [comment]
The re-installation of dependencies could be the behavior of ComfyUI-Manager. I just removed it in all `comfy3d` Docker images. (7e98e5a)

**Comment by YanWenKun** [comment]
Update:
I can't get `pt23` running on WSL2 Docker either. It's the same error `[F glutil.cpp:338] eglInitialize() failed`.

pffffffff...

**Comment by YanWenKun** [comment]
One thing for sure, that `eglInitialize() failed` is related to the deps required by Comfy3D.

* `pt22` uses [wheels compiled by me](https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/tag/v2)
* `pt23` uses wheels from [3D-Pack](https://github.com/MrForExample/Comfy3D_Pre_Builds/tree/b27af1a28d9f194cea1a137750e35ac698406e60/_Build_Wheels/_Wheels_linux_py311_cu121)
* `pt25` uses [wheels compiled by me](https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/tag/v5.1)

Good thing is that `pt23` works for you.

For anyone who got `[F glutil.cpp:338] eglInitialize() failed` and none of the above works, consider build the wheels yourself:
https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels

And I give up on searching the root cause of `[F glutil.cpp:338] eglInitialize() failed`, it's a maze...
