### ISSUE TITLE
你好，我尝试在linux下pull这个image，但是出现了报错failed to register layer: archive/tar: invalid tar header

### ISSUE THREAD

**Issue by coteejlizih** [YanWenKun/ComfyUI-Docker#7]
感谢你提供的镜像！这是我的报错
![微信图片_20231004211215](https://github.com/YanWenKun/ComfyUI-Docker/assets/143003009/7fff80d8-c728-4708-9eb0-8523afad4637)

**Comment by YanWenKun** [comment]
可能是缓存的问题，我刚刚push了一个新镜像，你可以试试清除缓存、重新下载

```
docker rmi yanwk/comfyui-boot:latest
docker image prune
docker pull yanwk/comfyui-boot:latest
```
